import requests
import json
import sys
from typing import Dict, Any
import config

# Configure stdout to handle UTF-8 formatting and print Unicode emojis without crashing on Windows
try:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass


def get_score_badge(score: int) -> str:
    """Returns a badge label based on the lead score."""
    if score >= 90:
        return "☄️ SUPER HOT LEAD"
    elif score >= 75:
        return "🔥 HOT LEAD"
    elif score >= 50:
        return "⚡ WARM LEAD"
    else:
        return "🌱 POTENTIAL LEAD"

def format_markdown_message(lead: Dict[str, Any]) -> str:
    """Formats a lead into a clean markdown message for Telegram or Console."""
    score = lead.get("score", 0)
    badge = get_score_badge(score)
    phone = lead.get("phone") or "No phone available"
    email = lead.get("email")
    opening_hours = lead.get("opening_hours")
    
    msg = (
        f"{badge} — *{score}/100*\n\n"
        f"*{lead['name']}*\n"
        f"📍 {lead['city']}, {lead['country']}\n"
    )
    if lead.get('rating') or lead.get('reviews_count'):
        rating = f"{lead.get('rating')}★" if lead.get("rating") else "N/A"
        reviews = f"{lead.get('reviews_count')} reviews" if lead.get("reviews_count") else "No reviews"
        msg += f"⭐ {rating} · {reviews}\n"
    msg += f"🌐 No website listed\n"
    msg += f"📞 Phone: `{phone}`\n"
    if email:
        msg += f"✉️ Email: `{email}`\n"
    if opening_hours:
        msg += f"⏰ Hours: `{opening_hours}`\n"
    fb_url = lead.get('facebook_search_url')
    if fb_url:
        msg += f"👥 [Search Facebook Page]({fb_url})\n"
    msg += (
        f"🗺️ [View on Google Maps]({lead.get('maps_url', '#')})\n"
        f"💰 High website potential"
    )
    return msg

def format_slack_payload(lead: Dict[str, Any]) -> Dict[str, Any]:
    """Formats a lead into Slack Block Kit payload."""
    score = lead.get("score", 0)
    badge = get_score_badge(score)
    phone = lead.get("phone") or "No phone available"
    email = lead.get("email")
    opening_hours = lead.get("opening_hours")
    maps_url = lead.get("maps_url") or "https://maps.google.com"
    
    rating_str = ""
    if lead.get('rating') or lead.get('reviews_count'):
        rating = f"{lead.get('rating')}★" if lead.get("rating") else "N/A"
        reviews = f"({lead.get('reviews_count')} reviews)" if lead.get("reviews_count") else "(No reviews)"
        rating_str = f"⭐ {rating} {reviews}\n"
        
    contact_str = f"📞 Phone: `{phone}`"
    if email:
        contact_str += f"\n✉️ Email: `{email}`"
    if opening_hours:
        contact_str += f"\n⏰ Hours: `{opening_hours}`"
    if lead.get('facebook_search_url'):
        contact_str += f"\n👥 *<{lead['facebook_search_url']}|Search Facebook Page>*"
        
    return {
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"{badge} ({score}/100)",
                    "emoji": True
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*<{maps_url}|{lead['name']}>*\n📍 {lead['city']}, {lead['country']}\n{rating_str}🌐 *No website listed*\n{contact_str}"
                }
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "💰 *High Website Potential* | Generated by Lead Gen Bot"
                    }
                ]
            },
            {
                "type": "divider"
            }
        ]
    }

def send_notification(lead: Dict[str, Any]) -> bool:
    """Dispatches lead details to the configured notification channel."""
    channel = config.NOTIFICATION_CHANNEL
    
    if channel == "telegram":
        return _send_telegram(lead)
    elif channel == "slack":
        return _send_slack(lead)
    else:
        # Default to console
        return _send_console(lead)

def _send_console(lead: Dict[str, Any]) -> bool:
    """Outputs formatted lead details to standard output."""
    score = lead.get("score", 0)
    badge = get_score_badge(score)
    phone = lead.get("phone") or "No phone available"
    email = lead.get("email")
    opening_hours = lead.get("opening_hours")
    
    # Beautiful CLI output with ANSI color codes
    cyan = "\033[96m"
    bold = "\033[1m"
    green = "\033[92m"
    yellow = "\033[93m"
    red = "\033[91m"
    reset = "\033[0m"
    
    color = red if score >= 90 else (yellow if score >= 75 else green)
    
    print("\n" + "=" * 50)
    print(f"{color}{bold}{badge} — {score}/100{reset}")
    print(f"{bold}{lead['name']}{reset}")
    print(f"📍 {lead['city']}, {lead['country']}")
    if lead.get('rating') or lead.get('reviews_count'):
        rating = f"{lead.get('rating')}★" if lead.get("rating") else "N/A"
        reviews = f"{lead.get('reviews_count')} reviews" if lead.get("reviews_count") else "No reviews"
        print(f"⭐ {rating} · {reviews}")
    print(f"🌐 No website listed")
    print(f"📞 Phone: {cyan}{phone}{reset}")
    if email:
        print(f"✉️ Email: {cyan}{email}{reset}")
    if opening_hours:
        print(f"⏰ Hours: {opening_hours}")
    if lead.get('facebook_search_url'):
        print(f"👥 Facebook Search: {cyan}{lead['facebook_search_url']}{reset}")
    print(f"🗺️ Maps URL: {lead.get('maps_url')}")
    print(f"💰 Website Potential: High")
    print("=" * 50 + "\n")
    return True

def _send_telegram(lead: Dict[str, Any]) -> bool:
    """Sends a markdown message to Telegram."""
    msg = format_markdown_message(lead)
    url = f"https://api.telegram.org/bot{config.TELEGRAM_BOT_TOKEN}/sendMessage"
    payload = {
        "chat_id": config.TELEGRAM_CHAT_ID,
        "text": msg,
        "parse_mode": "Markdown"
    }
    
    try:
        response = requests.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            return True
        else:
            print(f"Telegram error: Status {response.status_code} - {response.text}")
            print("Falling back to console print.")
            _send_console(lead)
            return False
    except Exception as e:
        print(f"Exception sending to Telegram: {str(e)}")
        _send_console(lead)
        return False

def _send_slack(lead: Dict[str, Any]) -> bool:
    """Sends block kit message to Slack."""
    payload = format_slack_payload(lead)
    
    try:
        response = requests.post(
            config.SLACK_WEBHOOK_URL,
            headers={"Content-Type": "application/json"},
            data=json.dumps(payload),
            timeout=10
        )
        if response.status_code in (200, 201):
            return True
        else:
            print(f"Slack error: Status {response.status_code} - {response.text}")
            print("Falling back to console print.")
            _send_console(lead)
            return False
    except Exception as e:
        print(f"Exception sending to Slack: {str(e)}")
        _send_console(lead)
        return False
